### ISSUE TITLE
Type androidx.compose.material3.pullrefresh.ArrowValues is defined multiple times

### ISSUE THREAD

**Issue by 1fexd** [Omico/androidx-compose-material3-pullrefresh#5]
Hi,

when I try to build a release error the task `:app:minifyReleaseWithR8` fails with the following error message: `Type androidx.compose.material3.pullrefresh.ArrowValues is defined multiple times: {my_project_location}/androidx-compose-material3-pullrefresh/library/build/intermediates/runtime_library_classes_jar/release/classes.jar:androidx/compose/material3/pullrefresh/ArrowValues.class,{my_home_dir}/.gradle/caches/transforms-3/ad60cd5cf5c1564926bb7f06eb667f86/transformed/material3-release-runtime.jar:androidx/compose/material3/pullrefresh/ArrowValues.class`

Could this mean that they have internally started implementing this functionality, but just haven't released it yet?

Using Kotlin 1.9.10,
Compose BOM 2023.10.0,
Compose Compiler 1.5.3,
material3-android:1.2.0-alpha09 (it seems like they have started implementing pullrefresh here)
material3:1.2.2

**Comment by Omico** [comment]
> Could this mean that they have internally started implementing this functionality, but just haven't released it yet?

Yes, it is. You can track it here. https://android.googlesource.com/platform/frameworks/support/+log/91bb8c1f81dcb031bda00fcd8e55f1e890b56f06..80156d02f56222d46dbad403c3adb812faaf62d6/compose/material3
The above link is the material3 1.2.0-alpha09 library that you use. It implements the pull refresh functionality there. 

Like I was saying in the README:

>This library only supports using composite build to import to your project because it will be archived when the official library is released.

This means if you use the non-stable version (1.2.0-alpha09) of the Material 3 library containing the official implementation, you should migrate it yourself. 

Since the changelog doesn't mention this, I assume they are still working on it and may change their API. Therefore, I will not update the README to provide detailed migration steps until the next official stable version is released.

https://developer.android.com/jetpack/androidx/releases/compose-material3#1.2.0-alpha09

**Comment by 1fexd** [comment]
Oh sorry, must have overseen that. Thanks!
